In [1]:
my_list = [4, 1, 5, 2]
my_list

[4, 1, 5, 2]

In [2]:
type(my_list)

list

In [3]:
my_mixed_list = [1, 2, 3, ['Boo!', True]]
type(my_mixed_list)

list

In [4]:
my_list * 2

[4, 1, 5, 2, 4, 1, 5, 2]

In [5]:
import numpy

In [6]:
my_array = numpy.array([4, 1, 5, 2])
my_array

array([4, 1, 5, 2])

In [7]:
type(my_list)

list

In [8]:
type(my_array)

numpy.ndarray

In [9]:
my_list * 2

[4, 1, 5, 2, 4, 1, 5, 2]

In [10]:
my_array * 2

array([ 8,  2, 10,  4])

In [11]:
my_coerced_array = numpy.array([1, 2, 3, 'Boo!'])
my_coerced_array

array(['1', '2', '3', 'Boo!'], dtype='<U11')

In [12]:
import numpy as np

In [13]:
import numpy as np
# numpy has a sqrt() function:
np.sqrt(my_array)

array([2.        , 1.        , 2.23606798, 1.41421356])

In [14]:
# Get second element... right?
my_array[2]

5

In [15]:
my_array

array([4, 1, 5, 2])

In [16]:
# *Now* let's get the second element
my_array[1]

1

In [17]:
# Get second through fourth elements... right?
my_array[1:3]

array([1, 5])

In [18]:
# *Now* get second through fourth elements
my_array[1:4]

array([1, 5, 2])

In [19]:
import pandas as pd

In [20]:
record_1 = np.array(['Jack', 72, False])
record_2 = np.array(['Jill', 65, True])
record_3 = np.array(['Billy', 68, False])
record_4 = np.array(['Susie', 69, False])
record_5 = np.array(['Johnny', 66, False])
        
roster = pd.DataFrame(data = [record_1, 
                              record_2, record_3, record_4,record_5],
                                columns = ['name', 'height', 'injury'])

roster

name height injury
0    Jack     72  False
1    Jill     65   True
2   Billy     68  False
3   Susie     69  False
4  Johnny     66  False

In [21]:
import seaborn as sns
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [22]:
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [23]:
import os

In [24]:
os.path.isfile('test-file.csv')

True

In [25]:
os.path.isfile('test-folder/test-file.csv')

True

In [26]:
# This will be False if you don't place a file one up from your current location
os.path.isfile('../test-file.csv')

False

In [27]:
star = pd.read_excel('datasets/star/star.xlsx')
star.head()

tmathssk  treadssk             classk  totexpk   sex freelunk   race  \
0       473       447        small.class        7  girl       no  white   
1       536       450        small.class       21  girl       no  black   
2       463       439  regular.with.aide        0   boy      yes  black   
3       559       448            regular       16   boy       no  white   
4       489       447        small.class        5   boy      yes  white   

   schidkn  
0       63  
1       20  
2       19  
3       69  
4       79

In [28]:
districts = pd.read_csv('datasets/star/districts.csv')
districts.head()

schidkn      school_name       county
0        1          Rosalia  New Liberty
1        2  Montgomeryville       Topton
2        3             Davy     Wahpeton
3        4         Steelton    Palestine
4        6       Tolchester      Sattley

In [29]:
star.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5748 entries, 0 to 5747
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   tmathssk  5748 non-null   int64 
 1   treadssk  5748 non-null   int64 
 2   classk    5748 non-null   object
 3   totexpk   5748 non-null   int64 
 4   sex       5748 non-null   object
 5   freelunk  5748 non-null   object
 6   race      5748 non-null   object
 7   schidkn   5748 non-null   int64 
dtypes: int64(4), object(4)
memory usage: 359.4+ KB


In [30]:
star.describe()

tmathssk     treadssk      totexpk      schidkn
count  5748.000000  5748.000000  5748.000000  5748.000000
mean    485.648051   436.742345     9.307411    39.836639
std      47.771531    31.772857     5.767700    22.957552
min     320.000000   315.000000     0.000000     1.000000
25%     454.000000   414.000000     5.000000    20.000000
50%     484.000000   433.000000     9.000000    39.000000
75%     513.000000   453.000000    13.000000    60.000000
max     626.000000   627.000000    27.000000    80.000000

In [31]:
star.describe(include = 'all')

tmathssk     treadssk             classk      totexpk   sex  \
count   5748.000000  5748.000000               5748  5748.000000  5748   
unique          NaN          NaN                  3          NaN     2   
top             NaN          NaN  regular.with.aide          NaN   boy   
freq            NaN          NaN               2015          NaN  2954   
mean     485.648051   436.742345                NaN     9.307411   NaN   
std       47.771531    31.772857                NaN     5.767700   NaN   
min      320.000000   315.000000                NaN     0.000000   NaN   
25%      454.000000   414.000000                NaN     5.000000   NaN   
50%      484.000000   433.000000                NaN     9.000000   NaN   
75%      513.000000   453.000000                NaN    13.000000   NaN   
max      626.000000   627.000000                NaN    27.000000   NaN   

       freelunk   race      schidkn  
count      5748   5748  5748.000000  
unique        2      3          NaN  
top          no  white          NaN  
freq       2973   3869          NaN  
mean        NaN    NaN    39.836639  
std         NaN    NaN    22.957552  
min         NaN    NaN     1.000000  
25%         NaN    NaN    20.000000  
50%         NaN    NaN    39.000000  
75%         NaN    NaN    60.000000  
max         NaN    NaN    80.000000

In [32]:
# First row, first column of DataFrame
roster.iloc[0,0]

'Jack'

In [33]:
# Second through fourth rows, first through third columns
roster.iloc[1:4, 0:3]

name height injury
1   Jill     65   True
2  Billy     68  False
3  Susie     69  False

In [34]:
# Select all rows in the name column
roster.loc[:, 'name']

0      Jack
1      Jill
2     Billy
3     Susie
4    Johnny
Name: name, dtype: object

In [35]:
roster.to_csv('output/roster-output-python.csv')
roster.to_excel('output/roster-output-python.xlsx')

ModuleNotFoundError: No module named 'openpyxl'