In [15]:
my_list = [1, 4, 9, 16]
my_list

[1, 4, 9, 16]

In [16]:
type(my_list)

list

In [17]:
my_mixed_list = [1, 2, 3, ['Boo!', True]]
type(my_mixed_list)

list

In [18]:
my_list * 2

[1, 4, 9, 16, 1, 4, 9, 16]

In [19]:
import numpy

In [20]:
my_array = numpy.array([1, 4, 9, 16])
my_array

array([ 1,  4,  9, 16])

In [21]:
type(my_list)

list

In [22]:
type(my_array)

numpy.ndarray

In [23]:
my_list * 2

[1, 4, 9, 16, 1, 4, 9, 16]

In [24]:
my_array * 2

array([ 2,  8, 18, 32])

In [25]:
my_coerced_array = numpy.array([1, 2, 3, 'Boo!'])
my_coerced_array

array(['1', '2', '3', 'Boo!'], dtype='<U11')

In [27]:
import numpy as np
    
# numpy has a sqrt() function:
np.sqrt(my_array)

array([1., 2., 3., 4.])

In [32]:
my_array[2]

9

In [31]:
my_array

array([ 1,  4,  9, 16])

In [34]:
# *Now* let's get the third element
my_array[2]

9

In [36]:
# Get second through fourth elements
my_array[1:3]

array([4, 9])

In [37]:
# *Now* get second through fourth elements
my_array[1:4]

array([ 4,  9, 16])

In [1]:
import numpy as np
import pandas as pd

In [2]:
record_1 = np.array(['Jack',72,False])
record_2 = np.array(['Jill',65,True])
record_3 = np.array(['Billy',68,False])
record_4 = np.array(['Susie',69,False])
record_5 = np.array(['Johnny',66,False])
        
roster = pd.DataFrame(data=[record_1,record_2,record_3,record_4,record_5],
        columns=['name','height_in','injury'])

roster  

name height_in injury
0    Jack        72  False
1    Jill        65   True
2   Billy        68  False
3   Susie        69  False
4  Johnny        66  False

In [12]:
#!conda install seaborn
import seaborn as sns

sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [15]:
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [19]:
iris['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [21]:
type(iris['sepal_length'])

pandas.core.series.Series

In [26]:
print(iris.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [27]:
print(iris.describe(include = 'all'))

        sepal_length  sepal_width  petal_length  petal_width    species
count     150.000000   150.000000    150.000000   150.000000        150
unique           NaN          NaN           NaN          NaN          3
top              NaN          NaN           NaN          NaN  virginica
freq             NaN          NaN           NaN          NaN         50
mean        5.843333     3.057333      3.758000     1.199333        NaN
std         0.828066     0.435866      1.765298     0.762238        NaN
min         4.300000     2.000000      1.000000     0.100000        NaN
25%         5.100000     2.800000      1.600000     0.300000        NaN
50%         5.800000     3.000000      4.350000     1.300000        NaN
75%         6.400000     3.300000      5.100000     1.800000        NaN
max         7.900000     4.400000      6.900000     2.500000        NaN


In [29]:
iris.iloc[1,2]

1.4

In [30]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [52]:
star = pd.read_excel('datasets/star/star.xlsx')
star.head()

id  tmathssk  treadssk             classk  totexpk   sex freelunk   race  \
0   1       473       447        small.class        7  girl       no  white   
1   2       536       450        small.class       21  girl       no  black   
2   3       463       439  regular.with.aide        0   boy      yes  black   
3   4       559       448            regular       16   boy       no  white   
4   5       489       447        small.class        5   boy      yes  white   

   schidkn  
0       63  
1       20  
2       19  
3       69  
4       79

In [60]:
districts = pd.read_csv('datasets/star/districts.csv')
districts.head()

schidkn      school_name       county
0        1          Rosalia  New Liberty
1        2  Montgomeryville       Topton
2        3             Davy     Wahpeton
3        4         Steelton    Palestine
4        5          Bonifay      Reddell

In [61]:
print(districts.head())

   schidkn      school_name       county
0        1          Rosalia  New Liberty
1        2  Montgomeryville       Topton
2        3             Davy     Wahpeton
3        4         Steelton    Palestine
4        5          Bonifay      Reddell


In [37]:
iris.loc[:,'sepal_width']

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal_width, Length: 150, dtype: float64

In [33]:
df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
     index=['cobra', 'viper', 'sidewinder'],
     columns=['max_speed', 'shield'])
df.loc['viper']

max_speed    4
shield       5
Name: viper, dtype: int64

In [36]:
df.loc[:,'max_speed']

cobra         1
viper         4
sidewinder    7
Name: max_speed, dtype: int64

In [39]:
roster['school_name'] = 'Padua'
roster

name height_in injury school_name
0    Jack        72  False       Padua
1    Jill        65   True       Padua
2   Billy        68  False       Padua
3   Susie        69  False       Padua
4  Johnny        66  False       Padua

In [40]:
print(roster)

     name height_in injury school_name
0    Jack        72  False       Padua
1    Jill        65   True       Padua
2   Billy        68  False       Padua
3   Susie        69  False       Padua
4  Johnny        66  False       Padua


In [45]:
roster['height_in'].dtype

dtype('O')

In [43]:
roster['height_cm'] = roster['height_in'] * 2.54
roster

TypeError: cannot convert the series to <class 'float'>

In [42]:
print(roster)

     name height_in injury school_name
0    Jack        72  False       Padua
1    Jill        65   True       Padua
2   Billy        68  False       Padua
3   Susie        69  False       Padua
4  Johnny        66  False       Padua


In [48]:
record_1 = np.array(['Jack',72.1,False])
record_2 = np.array(['Jill',65.6,True])
record_3 = np.array(['Billy',68.2,False])
record_4 = np.array(['Susie',69.5,False])
record_5 = np.array(['Johnny',66.8,False])
        
roster = pd.DataFrame(data=[record_1,record_2,record_3,record_4,record_5],
        columns=['name','height_in','injury'])

roster  

name height_in injury
0    Jack      72.1  False
1    Jill      65.6   True
2   Billy      68.2  False
3   Susie      69.5  False
4  Johnny      66.8  False

In [3]:
# First row, first column of DataFrame
roster.iloc[0, 0]

'Jack'

In [ ]:
# Second through fourth 