In [15]:
my_list = [1, 4, 9, 16]
my_list

[1, 4, 9, 16]

In [16]:
type(my_list)

list

In [17]:
my_mixed_list = [1, 2, 3, ['Boo!', True]]
type(my_mixed_list)

list

In [18]:
my_list * 2

[1, 4, 9, 16, 1, 4, 9, 16]

In [19]:
import numpy

In [20]:
my_array = numpy.array([1, 4, 9, 16])
my_array

array([ 1,  4,  9, 16])

In [21]:
type(my_list)

list

In [22]:
type(my_array)

numpy.ndarray

In [23]:
my_list * 2

[1, 4, 9, 16, 1, 4, 9, 16]

In [24]:
my_array * 2

array([ 2,  8, 18, 32])

In [25]:
my_coerced_array = numpy.array([1, 2, 3, 'Boo!'])
my_coerced_array

array(['1', '2', '3', 'Boo!'], dtype='<U11')

In [27]:
import numpy as np
    
# numpy has a sqrt() function:
np.sqrt(my_array)

array([1., 2., 3., 4.])

In [32]:
my_array[2]

9

In [31]:
my_array

array([ 1,  4,  9, 16])

In [34]:
# *Now* let's get the third element
my_array[2]

9

In [36]:
# Get second through fourth elements
my_array[1:3]

array([4, 9])

In [37]:
# *Now* get second through fourth elements
my_array[1:4]

array([ 4,  9, 16])