In [1]:
my_list = [1, 4, 9, 16]
my_list

[1, 4, 9, 16]

In [2]:
type(my_list)

list

In [3]:
my_mixed_list = [1, 2, 3, ['Boo!', True]]
type(my_mixed_list)

list

In [4]:
my_list * 2

[1, 4, 9, 16, 1, 4, 9, 16]

In [5]:
import numpy

In [6]:
my_array = numpy.array([1, 4, 9, 16])
my_array

array([ 1,  4,  9, 16])

In [7]:
type(my_list)

list

In [8]:
type(my_array)

numpy.ndarray

In [9]:
my_list * 2

[1, 4, 9, 16, 1, 4, 9, 16]

In [10]:
my_array * 2

array([ 2,  8, 18, 32])

In [11]:
my_coerced_array = numpy.array([1, 2, 3, 'Boo!'])
my_coerced_array

array(['1', '2', '3', 'Boo!'], dtype='<U11')

In [13]:
import math

In [14]:
my_array[2]

9

In [15]:
my_array

array([ 1,  4,  9, 16])

In [16]:
# *Now* let's get the third element
my_array[2]

9

In [17]:
# Get second through fourth elements
my_array[1:3]

array([4, 9])

In [18]:
# *Now* get second through fourth elements
my_array[1:4]

array([ 4,  9, 16])

In [19]:
import numpy as np
import pandas as pd

In [20]:
record_1 = np.array(['Jack',72,False])
record_2 = np.array(['Jill',65,True])
record_3 = np.array(['Billy',68,False])
record_4 = np.array(['Susie',69,False])
record_5 = np.array(['Johnny',66,False])
        
roster = pd.DataFrame(data=[record_1,record_2,record_3,record_4,record_5],
        columns=['name','height_in','injury'])

roster  

name height_in injury
0    Jack        72  False
1    Jill        65   True
2   Billy        68  False
3   Susie        69  False
4  Johnny        66  False

In [21]:
#!conda install seaborn
import seaborn as sns

sns.get_dataset_names()


Bad key savefig.frameon in file C:\Users\User\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 421 ('savefig.frameon : True')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.2/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.level in file C:\Users\User\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 472 ('verbose.level  : silent      # one of silent, helpful, debug, debug-annoying')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.3.2/matplotlibrc.template
or from the matplotlib source distribution

Bad key verbose.fileo in file C:\Users\User\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle, line 473 ('verbose.fileo  : sys.stdout  # a log filename, sys.stdout or sys.stderr')
You probably need to get an updated matplotlibrc file f

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [22]:
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [23]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [24]:
iris['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [25]:
type(iris['sepal_length'])

pandas.core.series.Series

In [26]:
print(iris.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [27]:
print(iris.describe(include = 'all'))

        sepal_length  sepal_width  petal_length  petal_width     species
count     150.000000   150.000000    150.000000   150.000000         150
unique           NaN          NaN           NaN          NaN           3
top              NaN          NaN           NaN          NaN  versicolor
freq             NaN          NaN           NaN          NaN          50
mean        5.843333     3.057333      3.758000     1.199333         NaN
std         0.828066     0.435866      1.765298     0.762238         NaN
min         4.300000     2.000000      1.000000     0.100000         NaN
25%         5.100000     2.800000      1.600000     0.300000         NaN
50%         5.800000     3.000000      4.350000     1.300000         NaN
75%         6.400000     3.300000      5.100000     1.800000         NaN
max         7.900000     4.400000      6.900000     2.500000         NaN


In [28]:
iris.iloc[1,2]

1.4

In [38]:
# First row, first column of DataFrame
roster.iloc[0, 0]

'Jack'

In [42]:
# Second through fourth rows, first through third columns
print(roster.iloc[1:4, 0:3])

    name height_in injury
1   Jill        65   True
2  Billy        68  False
3  Susie        69  False


In [46]:
roster.loc[:, 'name']

0      Jack
1      Jill
2     Billy
3     Susie
4    Johnny
Name: name, dtype: object